name: icon-automation
on:
  push:
    branches:
    - master
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - package.json

jobs:
  icon_automation:
    name: figma icon automation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
    - name: Figma Action
      uses: primer/figma-action@v1.0.0-alpha.2
      with:
        args: "format=svg outputDir=./src/"
      env:
        FIGMA_FILE_URL: ${{ secrets.FIGMA_FILE_URL }}
        FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
    - run: yarn generate
    - name: commit if changed
      run: |
        if [ -z "$(git status --porcelain)" ]; then
          echo "Clean!"
          exit 1
        else
          git config --global user.email "push@no-reply.github.com"
          git config --global user.name "GitHub Push Action"
          yarn version --patch
          git add .
          git commit -m "GitHub Push" -a
          git pull
          git push origin master
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
